-define(ATTRIB_RECORD, optional, transitive, partial, type, data, type_decoded, data_decoded, origin, as_path, next_hop, med, local_pref, atomic_aggregate, aggregator, transitive_unknown).
-record(attrib, {?ATTRIB_RECORD}).
